/var/log/mpd/*.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    create 0640 mpd mpd
    sharedscripts
    postrotate
        systemctl reload mpd > /dev/null 2>&1 || true
    endscript
}
